# Generated by Django 5.1.2 on 2024-10-19 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_asset_location_player_user_weeklyreport_expenses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_name',
        ),
        migrations.AlterField(
            model_name='player',
            name='active_business_id',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.business'),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_funds',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='player',
            name='experience_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_businesses_owned',
            field=models.IntegerField(default=0),
        ),
    ]
