# Generated by Django 5.1.2 on 2024-10-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_player_owwner_business_player_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIBusiness',
            fields=[
                ('aibusiness_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('financial_health', models.CharField(max_length=50)),
                ('growth_level', models.IntegerField()),
                ('failure_rate', models.FloatField()),
                ('business_status', models.CharField(max_length=50)),
                ('missed_deadlines', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='business',
            name='ai_owner',
        ),
        migrations.RemoveField(
            model_name='business',
            name='failure_rate',
        ),
        migrations.RemoveField(
            model_name='business',
            name='growth_level',
        ),
        migrations.RemoveField(
            model_name='business',
            name='missed_deadlines',
        ),
        migrations.DeleteModel(
            name='Competitor',
        ),
    ]
