# Generated by Django 5.1.2 on 2024-10-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_aibusiness_remove_business_ai_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='funds',
            field=models.IntegerField(default=0),
        ),
    ]
