# Generated by Django 5.1.2 on 2024-10-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_business_funds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expiration',
            field=models.IntegerField(default=3),
        ),
    ]
