# Generated by Django 5.1.2 on 2024-10-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_job_business_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_day', models.IntegerField(default=1)),
                ('current_week', models.IntegerField(default=1)),
                ('current_year', models.IntegerField(default=2024)),
            ],
        ),
    ]
