# Generated by Django 5.1.2 on 2024-10-28 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_run_game_init'),
        ('core', '0012_gamestate'),
    ]

    operations = [
    ]
