# Generated by Django 5.1.2 on 2024-10-28 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_0002_run_game_init_0012_gamestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='working_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.job'),
        ),
    ]
