# Generated by Django 5.1.2 on 2024-10-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_player_working_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='time_worked',
            field=models.IntegerField(default=0),
        ),
    ]
