# Generated by Django 5.1.2 on 2024-10-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_job_time_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_task',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
